/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutVideoRecordingRouteImport } from './routes/_layout/video-recording'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPsychologicalTestRouteImport } from './routes/_layout/psychological-test'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutCounselorChatRouteImport } from './routes/_layout/counselor-chat'
import { Route as LayoutAudioRecordingRouteImport } from './routes/_layout/audio-recording'
import { Route as LayoutAnalysisRouteImport } from './routes/_layout/analysis'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVideoRecordingRoute = LayoutVideoRecordingRouteImport.update({
  id: '/video-recording',
  path: '/video-recording',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPsychologicalTestRoute = LayoutPsychologicalTestRouteImport.update({
  id: '/psychological-test',
  path: '/psychological-test',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCounselorChatRoute = LayoutCounselorChatRouteImport.update({
  id: '/counselor-chat',
  path: '/counselor-chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAudioRecordingRoute = LayoutAudioRecordingRouteImport.update({
  id: '/audio-recording',
  path: '/audio-recording',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalysisRoute = LayoutAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analysis': typeof LayoutAnalysisRoute
  '/audio-recording': typeof LayoutAudioRecordingRoute
  '/counselor-chat': typeof LayoutCounselorChatRoute
  '/history': typeof LayoutHistoryRoute
  '/items': typeof LayoutItemsRoute
  '/psychological-test': typeof LayoutPsychologicalTestRoute
  '/settings': typeof LayoutSettingsRoute
  '/video-recording': typeof LayoutVideoRecordingRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analysis': typeof LayoutAnalysisRoute
  '/audio-recording': typeof LayoutAudioRecordingRoute
  '/counselor-chat': typeof LayoutCounselorChatRoute
  '/history': typeof LayoutHistoryRoute
  '/items': typeof LayoutItemsRoute
  '/psychological-test': typeof LayoutPsychologicalTestRoute
  '/settings': typeof LayoutSettingsRoute
  '/video-recording': typeof LayoutVideoRecordingRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/analysis': typeof LayoutAnalysisRoute
  '/_layout/audio-recording': typeof LayoutAudioRecordingRoute
  '/_layout/counselor-chat': typeof LayoutCounselorChatRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/psychological-test': typeof LayoutPsychologicalTestRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/video-recording': typeof LayoutVideoRecordingRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analysis'
    | '/audio-recording'
    | '/counselor-chat'
    | '/history'
    | '/items'
    | '/psychological-test'
    | '/settings'
    | '/video-recording'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analysis'
    | '/audio-recording'
    | '/counselor-chat'
    | '/history'
    | '/items'
    | '/psychological-test'
    | '/settings'
    | '/video-recording'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/analysis'
    | '/_layout/audio-recording'
    | '/_layout/counselor-chat'
    | '/_layout/history'
    | '/_layout/items'
    | '/_layout/psychological-test'
    | '/_layout/settings'
    | '/_layout/video-recording'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/video-recording': {
      id: '/_layout/video-recording'
      path: '/video-recording'
      fullPath: '/video-recording'
      preLoaderRoute: typeof LayoutVideoRecordingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/psychological-test': {
      id: '/_layout/psychological-test'
      path: '/psychological-test'
      fullPath: '/psychological-test'
      preLoaderRoute: typeof LayoutPsychologicalTestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/counselor-chat': {
      id: '/_layout/counselor-chat'
      path: '/counselor-chat'
      fullPath: '/counselor-chat'
      preLoaderRoute: typeof LayoutCounselorChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audio-recording': {
      id: '/_layout/audio-recording'
      path: '/audio-recording'
      fullPath: '/audio-recording'
      preLoaderRoute: typeof LayoutAudioRecordingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analysis': {
      id: '/_layout/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof LayoutAnalysisRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAnalysisRoute: typeof LayoutAnalysisRoute
  LayoutAudioRecordingRoute: typeof LayoutAudioRecordingRoute
  LayoutCounselorChatRoute: typeof LayoutCounselorChatRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPsychologicalTestRoute: typeof LayoutPsychologicalTestRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutVideoRecordingRoute: typeof LayoutVideoRecordingRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAnalysisRoute: LayoutAnalysisRoute,
  LayoutAudioRecordingRoute: LayoutAudioRecordingRoute,
  LayoutCounselorChatRoute: LayoutCounselorChatRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPsychologicalTestRoute: LayoutPsychologicalTestRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutVideoRecordingRoute: LayoutVideoRecordingRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
